# Subreddits joined by AccordingWarning7403
# Extracted from community list

- Adulting
- aiArt
- AIDungeon
- aigamedev
- aivideo
- aivideos
- androiddev
- AndroidGaming
- announcements
- Anthropic
- AppIdeas
- AskMarketing
- blender
- blocktales
- buildinpublic
- ChaotixAI
- chaotixapp
- chiptunes
- construct
- cozygames
- creative
- creativecoding
- CreativeProcess
- Creativity
- DeepGames
- Design
- DestroyMyGame
- developersIndia
- Entrepreneur
- facesinthings
- gameassets
- GameAudio
- GameDeals
- gamedesign
- gamedev
- GameDevelopment
- gamedevscreens
- gamejamlist
- gamejams
- gamemusic
- gamereviews
- Games
- gaming
- gamingsuggestions
- GenAI4all
- GenAlpha
- generative
- godot
- gtmengineering
- Hindi
- hinduism
- hobbygamedev
- honk
- HypeHypeApp
- incremental_games
- IndianMods
- IndieDev
- indiegamedevforum
- indiegames
- IndieGaming
- indiehackers
- inspiration
- interestingasfuck
- iosgaming
- iOSProgramming
- javascript
- JumpCat
- learnprogramming
- ledzeppelin
- lowendgaming
- marketing
- MobileGaming
- movies
- myog
- NewAuthor
- NewMods
- NewsOfTheStupid
- OpenAI
- OutOfTheLoop
- PartneredYoutube
- patientgamers
- pcmasterrace
- pikooai
- PixelArt
- playmygame
- playtesters
- podcasting
- PremierLeague
- programming
- PromptEngineering
- recruitinghell
- retrogaming
- roblox
- robloxgamedev
- roguelikedev
- rpg
- rpg_gamers
